..E...FEE
======================================================================
ERROR: test_list_int (__main__.Test03_max_temperature)
*** Test03 **** FUNCTION CALL: weather.max_temperature(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205') *** EXPECT: 74 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/test.py", line 43, in test_list_int
    r = weather.max_temperature(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205')
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/weather.py", line 19, in max_temperature
    if date[key]['t'] > x:
TypeError: string indices must be integers

======================================================================
ERROR: test_list_int (__main__.Test08_report_daily)
*** Test08 **** FUNCTION CALL: weather.report_daily(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205') *** EXPECT: <look in test.py Test08 variable = report> ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/test.py", line 93, in test_list_int
    r = weather.report_daily(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205')
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/weather.py", line 65, in report_daily
    display = display + f'{m:22}{tm:8}{t:13}{h:10}{r:10:2f}' + "\n"
ValueError: Invalid format specifier

======================================================================
ERROR: test_list_int (__main__.Test09_report_historical)
*** Test09 **** FUNCTION CALL: weather.report_historical(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}) *** EXPECT: <look in test.py Test09 variable = report> ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/test.py", line 110, in test_list_int
    r = weather.report_historical(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}})
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/weather.py", line 79, in report_historical
    m = calendar.month_name(int(h[4:6])) + " " + str(int(h[6:8])) + ", " + str(int(h[0:4]))
ValueError: invalid literal for int() with base 10: ''

======================================================================
FAIL: test_list_int (__main__.Test07_tot_rain)
*** Test07 **** FUNCTION CALL: weather.tot_rain(data={"20210203075501": {"t": 55, "h": 87, "r": 0}, "20210203090602": {"t": 63, "h": 84, "r": 0}, "20210203102903": {"t": 71, "h": 79, "r": 0}, "20210203125504": {"t": 72, "h": 69, "r": 0}, "20210203183905": {"t": 59, "h": 75, "r": 0}, "20210205044406": {"t": 57, "h": 68, "r": 0.01}, "20210205083307": {"t": 65, "h": 63, "r": 0.05}, "20210205122208": {"t": 73, "h": 56, "r": 0.11}, "20210205161109": {"t": 74, "h": 60, "r": 0.19}}, date='20210205') *** EXPECT: 0.36 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Desktop/CPSC223P/assignment_4-alextran55/test.py", line 84, in test_list_int
    self.assertEqual(0.36, r)
AssertionError: 0.36 != 0.0

----------------------------------------------------------------------
Ran 9 tests in 0.006s

FAILED (failures=1, errors=3)
